SELECT STUDIO.NAME, EMPNO, MOVIEEXEC.NAME, MOVIEEXEC.ADDRESS
FROM STUDIO, MOVIEEXEC
WHERE STUDIO.NAME IN (SELECT DISTINCT(SOUNDSTUDIO) FROM MOVIE, STUDIO WHERE SOUNDSTUDIO = NAME) AND PRESNO = CERTNO;