SELECT DISTINCT (TITLE), YEAR
FROM MOVIE,
(SELECT DIRECTORNO FROM MOVIE,MOVIEEXEC WHERE DIRECTORNO = CERTNO AND NETWORTH=(SELECT MAX(NETWORTH) FROM MOVIE, MOVIEEXEC WHERE DIRECTORNO = CERTNO))DIR,
(SELECT (STUDIO.NAME) STNAME FROM MOVIEEXEC, STUDIO WHERE PRESNO = CERTNO AND NETWORTH=(SELECT MIN(NETWORTH) FROM MOVIEEXEC, STUDIO WHERE PRESNO = CERTNO))STU,
(SELECT PRODUCERNO FROM MOVIE,MOVIEEXEC WHERE PRODUCERNO = CERTNO AND NETWORTH=(SELECT MIN(NETWORTH) FROM MOVIE, MOVIEEXEC WHERE PRODUCERNO = CERTNO))PRO
     
WHERE DIR.DIRECTORNO = MOVIE.DIRECTORNO AND STU.STNAME = MOVIE.studioName AND PRO.PRODUCERNO = MOVIE.PRODUCERNO;


