SELECT MOVIEEXEC.NAME, COUNT(DIRECTORNO), AVG(length) 
FROM MOVIE, MOVIEEXEC
WHERE DIRECTORNO = CERTNO AND MOVIE.DIRECTORNO IN (SELECT DIRECTORNO FROM MOVIE, MOVIEEXEC WHERE DIRECTORNO = CERTNO)
GROUP BY MOVIEEXEC.NAME;

