SELECT MOV.TITLE, MOV.YEAR
FROM (SELECT * FROM MOVIE WHERE TITLE  IN (SELECT MOVIETITLE FROM STARSIN WHERE STARNAME = 
(SELECT STARNAME FROM STARSIN WHERE GURANTEE=(SELECT MAX(GURANTEE) FROM  STARSIN))))MOV
WHERE MOV.LENGTH = (SELECT MAX(LENGTH) FROM MOVIE WHERE TITLE  IN 
(SELECT MOVIETITLE FROM STARSIN WHERE STARNAME = 
(SELECT STARNAME FROM STARSIN WHERE GURANTEE =
(SELECT MAX(GURANTEE) FROM  STARSIN))))
OR MOV.YEAR = 
(SELECT min(movieyear) FROM STARSIN WHERE STARNAME = 
(SELECT STARNAME FROM STARSIN WHERE GURANTEE = 
(SELECT MAX(GURANTEE) FROM  STARSIN))); 